@echo off
echo Starting Easy Interview Project...
echo Activating virtual environment (.venv)...
call .venv\Scripts\activate
if %errorlevel% neq 0 (
    echo Error: Could not find .venv. Trying venv...
    call venv\Scripts\activate
)
echo Starting Django server on http://127.0.0.1:8000/ ...
echo (You can also access it on your phone using your computer's IP address)
python manage.py runserver 0.0.0.0:8000
pause
