@echo off
echo Starting Easy Interview Project...
echo Activating virtual environment (.venv)...
call .venv\Scripts\activate
if %errorlevel% neq 0 (
    echo Error: Could not find .venv. Trying venv...
    call venv\Scripts\activate
)
echo Starting Django server on http://127.0.0.1:8000/ ...
python manage.py runserver 127.0.0.1:8000
pause
