# Generated by Django 6.0.4 on 2026-04-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_interview_started_at_user_is_expert_liveroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveroom',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveroom',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
    ]
