# Generated by Django 4.2.14 on 2026-04-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_liveroom_scheduled_at_liveroom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='site_base_url',
            field=models.URLField(default='http://127.0.0.1:8000', help_text='The public URL of your site (e.g. https://easy-interview.onrender.com)'),
        ),
    ]
